# Generated by Django 2.0.2 on 2018-02-28 19:41

import GCprofile.helpers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
                ('country', models.CharField(default='Canada', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OrgTier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=150)),
                ('name_fr', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gcID', models.CharField(max_length=100, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=75)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=GCprofile.helpers.unique_filepath)),
                ('mobile_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('office_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('title_en', models.CharField(max_length=150)),
                ('title_fr', models.CharField(max_length=150)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GCprofile.Address')),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GCprofile.OrgTier')),
                ('supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GCprofile.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='orgtier',
            name='ownerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.ProtectedError, to='GCprofile.Profile'),
        ),
    ]
