version: '3'

services:
  db:
    image: postgres
    volumes:
      - ./db_volume:/var/lib/postgresql/data
  web:
    build: .
    environment:
      - DEBUG=True
      - ALLOWED_HOST=*
      - SECRET_KEY=AFGcl457890liknoKpQOm42jwh
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    ports:
      - "8080:8000"
    depends_on:
      - db
