version: '3'

services:
  db:
    image: postgres
    volumes:
      - ./db_volume:/var/lib/postgresql/data
  web:
    build: .
    environment:
      - DEBUG=True
      - ALLOWED_HOST=*
      - SECRET_KEY=AFGcl457890liknoKpQOm42jwh
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - OIDC_USERINFO_ENDPOINT=http://172.20.0.3:8000/openid/userinfo
    ports:
      - "8080:8000"
    depends_on:
      - db
      - image
  image:
    build: ./image-server
    volumes:
      - ./volumes/upload:/usr/share/nginx/html/upload
    environment:
      - TITLE=Meerkat-Image-Server
      - DOMAIN=https://avatar.gccollab.ca
      - LOWPROFILE=True
    ports:
    - "80:80"

