# Generated by Django 2.0.3 on 2018-03-13 19:18

from django.db import migrations, models
import django.db.models.deletion
import profile.helpers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
                ('country', models.CharField(default='Canada', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=150)),
                ('name_fr', models.CharField(max_length=150)),
                ('acronym_fr', models.CharField(max_length=10)),
                ('acronym_en', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='OrgTier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=150)),
                ('name_fr', models.CharField(max_length=150)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Org_Tiers', to='profile.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('gcID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=profile.helpers.unique_filepath)),
                ('mobile_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('office_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('title_en', models.CharField(blank=True, max_length=150, null=True)),
                ('title_fr', models.CharField(blank=True, max_length=150, null=True)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profile.Address')),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profile.OrgTier')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Employees', to='profile.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='orgtier',
            name='ownerID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Owner_of_Org_Tiers', to='profile.Profile'),
        ),
    ]
